### ISSUE TITLE
Rename deprecated host names

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-deploy#124]
Compose -> Builder
Perform -> Player
Analyzer -> Analytics
Explore/r -> Library

Auth or Authentication?

**Comment by spaenleh** [comment]
@pyphilia, I removed the old names from the files in [this commit](https://github.com/graasp/graasp-deploy/commit/5a932f7fcde421cf9ef6494df3811da14b290b8d), I think we can close this as done !
