### ISSUE TITLE
Use Github deployment environments

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-deploy#152]
We can dedupe a lot of code and passed inputs / variables / secrets by using Github's native [environments feature](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)

**Comment by pyphilia** [comment]
Secrets from env in reusable workflows https://github.com/actions/runner/issues/1490
What I learned today
- you cannot setup an environment from a caller for a callee, so you need to pass the environment as input for the callee to use and set it up. The environment used will be the caller's repo's.
- the callee can use the environment's variables freely.
- the callee cannot use the environment's  secret freely. Instead, the callee needs to explicitly pass them to the callee -> so explicitly it will use the environment's.

**Comment by dialexo** [comment]
@pyphilia Thank you for your exploratory work. I'm surprised environments specific variables can be accessed from another repo. Have we found a way to share secrets without explicitly listing them as such? If not I guess we still may want to centralize deployment concerns in this repo at some point

**Comment by spaenleh** [comment]
Done as we have moved the deploy workflow for the backend inside the backend repo
